# -*- coding: utf-8 -*-
"""ML_framework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MwjiZuDiNiSFzWaSRUmK-VlPqFItV9ZZ
"""

from google.colab import drive

drive.mount("/content/gdrive")  
!pwd  # show current path

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/gdrive/MyDrive/AD2022"
!ls  # show current directory

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

red_wine = pd.read_csv('winequality_red.csv', header = 0)
y = red_wine['class']
X = red_wine.drop('class', axis=1)

"""Separación y evaluación del modelo con un conjunto de prueba y un conjunto de validación (Train/Test/Validation)"""

'''
Split para obtener conjunto de prueba y de entrenamiento. 

:Prueba: = (20%)
'''
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
'''
Split para obtener conjunto de validación. 

:Validación: = (20%)
:Entrenamiento: = (60%)
'''
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=1)

rfc = RandomForestClassifier(random_state=42, 
                             n_estimators=1000,
                             criterion="entropy",
                             max_depth=None,
                             bootstrap=True
                             )



"""Evaluación de set de pruebas y set de validación

Diagnóstico y explicación el grado de bias o sesgo: bajo medio alto
"""